baseURL = "https://infuzzwetrust.github.io/infuzzwetrust"
locale = "en-us"
title = "InFuzzWeTrust"
theme = "hugo-classic"

relativeURLs = true
canonifyURLs = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Fonts
[params]
  customCSS = ["css/custom-fonts.css"]