# Site Settings
baseURL = "https://infuzzwetrust.github.io/infuzzwetrust/"
languageCode = "en-us"
title = "InFuzzWeTrust"
description = "A simple, minimal blog for those who love text."
theme = "hugo-classic"
relativeURLs = true
canonifyURLs = true
enableEmoji = true

# Cache settings
[caches]
  [caches.images]
    dir = ":cacheDir/images"

# Custom parameters
[params]
  customCSS = ["css/custom-fonts.css", "css/theme-override.css"]
  footer = "@infuzzwetrust | [Github](https://github.com/infuzzwetrust) | Built using [hugo-classic](https://github.com/goodroot/hugo-classic) theme."

# Menu

[[menu.main]]
name = "Menu"       # Top-level dropdown
url = "#"           # Not a real page
weight = 1
identifier = "main-dropdown"

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  parent = "main-dropdown"

#  [[menu.main]]
#  name = "About"
#  url = "/about/"
#  weight = 2
#  parent = "main-dropdown"

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3
  parent = "main-dropdown"

  [[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 4
  parent = "main-dropdown"

#  [[menu.main]]
#  name = "Tags"
#  url = "/tags/"
#  weight = 5
#  parent = "main-dropdown"

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

# Markdown / Goldmark settings
[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# Permalinks
[permalinks]
    post = "/post/:year/:month/:day/:slug/"

# Ignore unnecessary files
# ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

# Google Analytics (empty for now)
googleAnalytics = ""
footnotereturnlinkcontents = " ↩"